#!/bin/sh
cd ..

# First execute with no branch table
echo -e "First running with no dynamic prediction"
read temp

java com.fitzgerald.simulator.processor.Simulator benchmarks/branchTableBenefit.asm --no-status --no-branch-table

echo -e "\nNow running with dynamic prediction enabled"
read temp

java com.fitzgerald.simulator.processor.Simulator benchmarks/branchTableBenefit.asm --no-status

cd launchers
